# Backend Dockerfile
FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache curl

COPY package*.json ./

RUN npm install

COPY . /app

RUN npm run tsc:backend # Compile TypeScript files

RUN ls -l /app
RUN ls -l /app/dist

EXPOSE 3002

CMD ["node", "/app/dist/backend/server.js"]